# Generated by Django 5.2.1 on 2025-06-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_language_question_languages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='question',
            name='input',
        ),
        migrations.RemoveField(
            model_name='question',
            name='output',
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='question_path',
            field=models.CharField(blank=True, help_text='Path to the markdown file containing the question statement', max_length=500, null=True),
        ),
    ]
