# Generated by Django 5.2.1 on 2025-06-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_rename_question_question_title_remove_question_input_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('arrays', 'Arrays'), ('strings', 'Strings'), ('linked_lists', 'Linked Lists'), ('trees', 'Trees'), ('graphs', 'Graphs'), ('dynamic_programming', 'Dynamic Programming'), ('recursion', 'Recursion'), ('greedy', 'Greedy Algorithms'), ('backtracking', 'Backtracking'), ('sorting', 'Sorting')], default='arrays', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='languages',
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ManyToManyField(default=1, related_name='topics', to='questions.topic'),
        ),
        migrations.AddField(
            model_name='question',
            name='languages',
            field=models.ManyToManyField(default=1, related_name='questions', to='questions.language'),
        ),
    ]
