# Generated by Django 5.2.1 on 2025-06-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_topic_remove_question_languages_question_topic_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_path',
        ),
        migrations.RemoveField(
            model_name='question',
            name='test_cases',
        ),
        migrations.RemoveField(
            model_name='question',
            name='topic',
        ),
        migrations.AddField(
            model_name='question',
            name='question_s3_key',
            field=models.CharField(blank=True, help_text='S3 key for the markdown question file', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='questions', to='questions.topic'),
        ),
        migrations.AlterField(
            model_name='question',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='questions', to='questions.language'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['difficulty', 'created_at'], name='questions_q_difficu_ba254f_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['title'], name='questions_q_title_4188d3_idx'),
        ),
    ]
