# Generated by Django 5.2.1 on 2025-06-29 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_question_options_remove_question_question_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('cpp', 'C++')], default='python', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic',
            field=models.CharField(choices=[('arrays', 'Arrays'), ('strings', 'Strings'), ('linked_lists', 'Linked Lists'), ('trees', 'Trees'), ('graphs', 'Graphs'), ('dynamic_programming', 'Dynamic Programming'), ('recursion', 'Recursion'), ('greedy', 'Greedy Algorithms'), ('backtracking', 'Backtracking'), ('sorting', 'Sorting')], default='arrays', max_length=100, unique=True),
        ),
    ]
