# Generated by Django 5.2.1 on 2025-07-02 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_alter_language_name_alter_topic_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_s3_key', models.TextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='questions.language')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='questions.question')),
            ],
        ),
    ]
