# Generated by Django 5.2.1 on 2025-06-01 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0002_testcase_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='input',
            new_name='input_path',
        ),
        migrations.RenameField(
            model_name='testcase',
            old_name='output',
            new_name='output_path',
        ),
    ]
